# Generated by Django 5.2.3 on 2025-07-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('Retrato simple', 'Retrato simple'), ('Cuerpo completo', 'Cuerpo completo'), ('Diseño de personaje', 'Diseño de personaje'), ('Pareja', 'Pareja / Duo'), ('NSFW', 'NSFW Personalizado')], max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('referencias', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
